name: build wheels

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: wheels-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wheels:
    name: Build wheels for ${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    permissions:
      contents: read  # to check out the repository
    strategy:
      matrix:
        PYTHON_VERSION: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Build wheels
        run: pip wheel --no-deps -w wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bedspec-wheels-${{ matrix.PYTHON_VERSION }}
          path: ./wheelhouse/bedspec*.whl
          if-no-files-found: error
